import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Arrow, CompanyLayout, ProjectInvitation } from './CompanyLayout';
import { services, serviceFromQuery } from './companyData';
import { siteConfig } from '@/lib/site-config';
import { createProjectBrief, type ProjectBrief } from './contactBrief';

export function ServicesPage() {
  return <CompanyLayout page="services" title="Engineering services"><header className="co-page-heading co-shell"><p className="co-label">Built with Serendepify</p><h1>Bring the problem.<br /><em>Let’s build from there.</em></h1><p>A new product, a better workflow, or a system that needs attention. We work with you to define the scope and build what’s needed.</p><a className="co-button co-button-ink" href="/contact">Discuss a project <Arrow /></a></header><div className="co-shell co-service-details">{services.map(service => <section key={service.id} id={service.id} aria-labelledby={`${service.id}-title`}><span className="co-label">{service.number} / Services</span><div><h2 id={`${service.id}-title`}>{service.title}</h2><p>{service.detail}</p><div className="co-deliverables"><span className="co-label">What we can deliver</span><p>{service.deliverables}</p></div><div className="co-actions"><a className="co-text-link" href={`/contact?service=${service.id}`}>Talk about your project <Arrow /></a><a className="co-text-link co-muted-link" href={service.exampleHref}>{service.example} <Arrow /></a></div></div></section>)}</div><section className="co-process co-section"><div className="co-shell"><p className="co-label">How we work together</p><h2>Know what’s next.</h2><div>{[{title:'Find the useful scope',body:'Understand the problem, users, and constraints. Agree what the first piece of work needs to achieve.'},{title:'Build something you can use',body:'Work in reviewable steps. Put the product in front of you early, and use feedback to guide the next step.'},{title:'Get it into your hands',body:'Verify the agreed work, prepare the release, and leave you with the access and documentation to carry it forward.'}].map((step,index)=><article key={step.title}><span>0{index+1}</span><h3>{step.title}</h3><p>{step.body}</p></article>)}</div></div></section><ProjectInvitation /></CompanyLayout>;
}

export function CompanyPage() {
  return <CompanyLayout page="company" title="The company"><header className="co-page-heading co-shell"><p className="co-label">Serendepify / Accra, Ghana</p><h1>Curiosity has<br /><em>a day job.</em></h1><p>We build our own software products and work with other teams to build theirs.</p></header><section className="co-shell co-about"><div className="co-about-mark" aria-hidden="true">s<span>✳</span></div><div><h2>Different problems.<br />A hands-on approach.</h2><p>GroundControl began with the work of running applications. Haven makes room for exploring spaces and furniture. RentAWeekend brings planning and local help into everyday life in Ghana.</p><p>Those products give us room to experiment, make decisions, and work through the details of building software people can use. We bring that experience to client projects, too.</p><div className="co-founder"><p className="co-label">The person behind Serendepify</p><h3>Edward Twumasi</h3><p>Engineer and creator, based in Accra.</p><a className="co-text-link" href="https://precisionxyz.serendepify.com/">Edward’s work & writing <Arrow /></a></div><a className="co-text-link" href="/products">Explore the products <Arrow /></a></div></section><ProjectInvitation /></CompanyLayout>;
}

export function ContactPage() {
  const [brief, setBrief] = useState<ProjectBrief>(() => ({name:'', email:'', service:serviceFromQuery(window.location.search), project:'', timing:''}));
  const [prepared, setPrepared] = useState(false);
  const draftHeading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (prepared) draftHeading.current?.focus(); }, [prepared]);
  const [copyStatus, setCopyStatus] = useState('');
  const message = createProjectBrief(brief, siteConfig.contactEmail);
  function update(key: keyof ProjectBrief, value: string) { setBrief(current=>({...current,[key]:value})); setPrepared(false); setCopyStatus(''); }
  function prepare(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPrepared(true); }
  async function copyBrief() { try { await navigator.clipboard.writeText(message.body); setCopyStatus('Brief copied. You can paste it into an email.'); } catch { setCopyStatus('Copy wasn’t available. Select the brief below and copy it manually.'); } }
  return <CompanyLayout page="contact" title="Discuss a project"><section className="co-shell co-contact"><div className="co-contact-intro"><p className="co-label">Work with Serendepify</p><h1>What’s on<br /><em>your mind?</em></h1><p>Tell us what you’re building, what needs improving, or where you’re stuck. A few sentences are enough to start.</p><div className="co-contact-direct"><span className="co-label">Prefer a simple email?</span><a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail} <Arrow /></a><p>Based in Accra, Ghana · GMT</p></div></div><div className="co-brief-form"><form onSubmit={prepare}><div className="co-form-row"><label>Your name<input name="name" autoComplete="name" value={brief.name} onChange={e=>update('name',e.target.value)} required maxLength={100} /></label><label>Email<input name="email" type="email" autoComplete="email" value={brief.email} onChange={e=>update('email',e.target.value)} required maxLength={200} /></label></div><label>What kind of help?<select name="service" value={brief.service} onChange={e=>update('service',e.target.value)}>{services.map(service=><option key={service.id} value={service.id}>{service.title}</option>)}<option value="not-sure">Let’s work that out</option></select></label><label>Tell us about the project<textarea name="project" rows={5} value={brief.project} placeholder="What are you trying to do? What exists already?" onChange={e=>update('project',e.target.value)} required maxLength={4000} /></label><label>Any timing in mind? <span>(optional)</span><input name="timing" value={brief.timing} placeholder="A deadline, a rough window, or still exploring" onChange={e=>update('timing',e.target.value)} maxLength={200}/></label><p className="co-form-note">This prepares an email draft. Nothing is sent until you send it from your email app.</p><button className="co-button co-button-ink" type="submit">Prepare my brief <Arrow /></button></form>{prepared && <section className="co-prepared" aria-labelledby="draft-title"><h2 ref={draftHeading} id="draft-title" tabIndex={-1}>Your brief is ready.</h2><p>Open it in your email app, or copy it and email us directly.</p><div className="co-actions"><a className="co-button co-button-coral" href={message.href}>Open email draft <Arrow /></a><button className="co-text-link" onClick={copyBrief}>Copy brief</button></div><details><summary>Read your brief</summary><pre>{message.body}</pre></details><p role="status">{copyStatus}</p></section>}</div></section></CompanyLayout>;
}

export function NotFoundPage() {
  return <CompanyLayout title="Page not found"><section className="co-page-heading co-shell"><p className="co-label">404 / A wrong turn</p><h1>Let’s get you<br /><em>somewhere useful.</em></h1><div className="co-actions"><a className="co-button co-button-ink" href="/products">Explore products <Arrow /></a><a className="co-button co-button-coral" href="/services">Explore services <Arrow /></a></div></section></CompanyLayout>;
}
